import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./Provider";

export const metadata: Metadata = {
  title: "ToDoList",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images.png" sizes="any" />
        <link rel="icon" type="image/png" href="/images.png" sizes="32x32" />
        <link rel="apple-touch-icon" href="/images.png" />
      </head>
      <body className="bg-gray-700">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
